#!/usr/bin/env python3

"""
Author: Michelle Kleisman

Date: 30-06-2025

Description: Script to determine which barcodes in the scRNaseq data set
contain a mutation at the DDOST hotspot location (chr1:20655484)

Input files: alt.mtx, souporcell_merged_sorted_vcf.vcf.gz and barcodes.tsv 
Output: out_file, contains all barcodes with a variant at the target location 
"""


# Parameter definitions
RESULTS_DIR = "/hpc/pmc_kuiper/HypermutatedALL_project/RESULTS/scRNAseq/DDOST/"
LIB_NAME = "LX447"
VCF_PATH = RESULTS_DIR + "souporcell_merged_sorted_vcf.vcf.gz"
ALT_MTX_PATH = RESULTS_DIR + "alt.mtx"
BARCODES_PATH = RESULTS_DIR + "barcodes.tsv"
TARGET_LOCATION = "chr1:20655484"
OUT_FILE = RESULTS_DIR + LIB_NAME + "_barcodesWithALTreadsInDDOST.tsv"


# Import statements
import gzip
from scipy.io import mmread
import pandas as pd


# Functions
def get_variant_index(vcf_path, coords):
    """ Find the 0-based row index of the target variant in the VCF file

    Keyword parameters
    vcf_path, str: path to the merged VCF file generated by Souporcell (.gz)
    coords, str: location of the target variant in format "chrX:pos"

    Returns
    index, int: 0-based row index of the target variant. Value None is 
                returned if the variant is not present in the VCF file
    """
    variant_idx = None
    with gzip.open(vcf_path, "rt") as in_vcf:
        
        # Skip header lines
        for line in in_vcf:
            if line.startswith("##"):
                continue
            elif line.startswith("#CHROM"):
                break

        # Enumerate all VCF entries and obtain chr:pos info
        for idx, line in enumerate(in_vcf): 
            chrom, pos = line.strip().split('\t')[0:2]

            # Determine if the target variant is present
            if chrom == coords.split(":")[0] and pos == coords.split(":")[1]:
                print(f"Found target variant at VCF index {idx} (0-based)")
                variant_idx = idx
                break
            else:
                continue
    return variant_idx

def get_barcodes_with_alt_reads(alt_mtx_path, barcodes_path, var_idx):
    """ Get barcodes and ALT counts for a specific variant index

    Keyword parameters
    alt_mtx_path, str: path to the sparse matrix of alt allele counts with three 
                       columns: variant_idx in the VCF file, barcodes_idx in the 
                       barcodes file and the ALT count observed for that combination
    barcodes_path, str: path to the barcodes file of the scRNAseq data
    var_idx, int: 0-based row index of the target variant in the VCF file

    Returns:
    matches, list: contains the barcodes which show a ALT count > 0 to the variant
                   target location, format: [(bc1, count1), (bc2, count2), etc]

    Notes:
    Indices in .mtx files are 1-based. However using mmread, indices are 
    automatically converted to 0-based. Thus, variant_idx and barcode_idx match 
    to correctly determine barcodes with alt count > 0  
    """
    # Parse alt counts and barcodes
    alt = mmread(alt_mtx_path).tocoo()
    barcodes = pd.read_csv(barcodes_path, header=None)[0].tolist()

    # Efficiently find indices where row == variant_idx and count > 0
    # Returns an array with True/False of which rows match conditions
    matching_idx = (alt.row == var_idx) & (alt.data > 0)
    cols = alt.col[matching_idx]
    counts = alt.data[matching_idx]
    
    # Combine column indices with barcode names
    matches = [(barcodes[col], int(count)) for col, count in zip(cols, counts)]
    return matches

def write_to_tsv(matches, out_file):
    """ Writes barcodes with ALT counts at target location to out TSV file
    
    Keyword parameters:
    matches, list: contains the barcodes which show a ALT count > 0 to the DDOST 
                   hotspot location, format: [(bc1, count1), (bc2, count2), etc]
    out_file, str: path to the output .tsv file where the information, stored in 
                   matches, will be written to
    """
    with open(out_file, "w") as out_tsv:
        out_tsv.write("barcode\talt_count\n")
        for barcode, count in matches:
            out_tsv.write(f"{barcode}\t{count}\n")
    return


if __name__ == '__main__':

    # Determine the variant idx in the VCF file
    variant_idx = get_variant_index(VCF_PATH, TARGET_LOCATION)
    if variant_idx is None:
        raise ValueError("Variant at target location not found in VCF")

    # Determine which barcodes have an alt count > 0 to the VCF entry
    else:
        matches = get_barcodes_with_alt_reads(ALT_MTX_PATH, BARCODES_PATH, variant_idx)
        if not matches:
            print(f"No barcodes with ALT reads at target location {TARGET_LOCATION}")
        else:
            write_to_tsv(matches, OUT_FILE)
            print(f"{len(matches)} barcodes found with ALT reads at target location")


